#!/bin/bash
# Restore script generated by install-dual-gpu-hardened.sh
BACKUP_DIR="$(dirname "$0")"
TIMESTAMP="20260104_182047"

echo "Restoring Ollama GPU config from backup ${TIMESTAMP}..."

if [[ -f "${BACKUP_DIR}/gpu-stability.conf.${TIMESTAMP}.bak" ]]; then
    sudo cp "${BACKUP_DIR}/gpu-stability.conf.${TIMESTAMP}.bak" /etc/systemd/system/ollama.service.d/gpu-stability.conf
    sudo rm -f /etc/systemd/system/ollama.service.d/dual-gpu.conf 2>/dev/null
    sudo systemctl daemon-reload
    sudo systemctl restart ollama
    echo "Restored. Check: systemctl status ollama"
else
    echo "ERROR: Backup file not found!"
    exit 1
fi
