#!/bin/bash
# OBS Recording Test Script

echo "=== OBS RECORDING TEST ==="
echo ""
echo "This will test OBS recording performance"
echo ""
echo "To test OBS:"
echo "  1. Open OBS Studio"
echo "  2. Add Display Capture or Window Capture"
echo "  3. Settings → Output:"
echo "     - Recording Path: /tmp/obs-test"
echo "     - Encoder: x264 or AMF"
echo "     - Bitrate: 6000 Kbps"
echo "  4. Settings → Video:"
echo "     - Base: 1920x1080"
echo "     - Output: 1920x1080"
echo "     - FPS: 60"
echo "  5. Start Recording for 30 seconds"
echo "  6. Check: /tmp/obs-test for output file"
echo ""
echo "Monitoring during recording:"
echo "  • CPU usage: htop"
echo "  • GPU usage: radeontop"
echo "  • FPS: OBS Stats window"
