#!/bin/bash
# OBS Recording Test & Optimization Guide

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         OBS RECORDING TEST & OPTIMIZATION GUIDE           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "BEST OBS SETTINGS FOR YOUR MAC PRO 2019:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OUTPUT SETTINGS (Settings → Output):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recording:"
echo "  • Type: Standard"
echo "  • Recording Path: /tmp/obs-test (fast NVMe)"
echo "  • Encoder: AMD AMF H.264 (GPU) OR x264 (CPU)"
echo "  • Rescale Output: 1920x1080"
echo "  • Rate Control: CBR"
echo "  • Bitrate: 8000 Kbps (1080p60)"
echo "  • Keyframe Interval: 2"
echo "  • Preset: Quality (AMF) or veryfast (x264)"
echo "  • Profile: high"
echo "  • Tune: none"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "VIDEO SETTINGS (Settings → Video):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Base Canvas: 1920x1080"
echo "  • Output Resolution: 1920x1080"
echo "  • Downscale Filter: Lanczos"
echo "  • FPS: 60"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ADVANCED SETTINGS (Settings → Advanced):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Process Priority: High"
echo "  • Color Format: NV12"
echo "  • Color Space: 709"
echo "  • Color Range: Partial"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "GPU SELECTION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Use RX 6900 XT (card2) for encoding - More powerful"
echo "  • Use W5700X (card1) for display if needed"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TESTING PROCEDURE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Open OBS Studio"
echo "2. Add Source: Display Capture or Window Capture"
echo "3. Apply settings above"
echo "4. Start Recording"
echo "5. Record for 30 seconds"
echo "6. Check output file in /tmp/obs-test"
echo "7. Monitor performance:"
echo "   • CPU: htop or btop"
echo "   • GPU: radeontop or nvtop"
echo "   • FPS: OBS Stats (View → Stats)"
echo ""
echo "EXPECTED PERFORMANCE:"
echo "  • FPS: 60 (stable)"
echo "  • CPU Usage: <30% (with GPU encoding)"
echo "  • GPU Usage: 50-80% (encoding GPU)"
echo "  • File Size: ~30MB for 30 seconds (8000 Kbps)"
